# Generated by Django 6.0 on 2026-01-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=30, unique=True)),
                ('edificio', models.CharField(blank=True, default='', max_length=50)),
                ('capacidad', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['clave'],
            },
        ),
    ]
