# Generated by Django 6.0 on 2026-01-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_aula'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=30)),
                ('nombre_materia', models.CharField(max_length=120)),
                ('grado', models.PositiveSmallIntegerField()),
                ('grupo', models.CharField(max_length=5)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['grado', 'grupo', 'nombre_materia'],
                'unique_together': {('grado', 'grupo', 'nombre_materia')},
            },
        ),
    ]
