# Generated by Django 6.0 on 2026-01-05 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0004_materiagrupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.aula')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.docente')),
                ('materia_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.materiagrupo')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.periodo')),
            ],
            options={
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
    ]
